# Exercise 1: Identifying Data, Information, and Knowledge

While the lesson provided an overview of what data was, in this exercise you'll be able to explore through a hands on example, what data is, why it's important, and how it can be used to derive information, and eventually knowledge. The following exercises will use the latest Stack Overflow Developer Survey dataset to provide hands-on experience with these concepts. 


## Step 1: Gathering Data
In this step, we will extract data from the latest 2025 Stackoverflow Survey Results. These surveys often function as a benchmark for industry experts to help them understand the latest trends, patterns, and experiences around development across industries. As per Stackoverflow itself: "the survey is the deifnitive report on the state of software devleopment." 

For more information, including raw data files, visit: https://survey.stackoverflow.co/

Historical records are also available.

We'll start by importing the necessary libraries we need to do this. Note that these tools will be covered in further detail across later lessons and lectures. For now, the requirement of this exercise is simply to follow along and fill in the blank variables for the queries.

In [3]:
%%capture
%pip install notebook duckdb jupysql matplotlib duckdb-engine;
%config SqlMagic.autopandas = True;
%config SqlMagic.feedback = False;
%config SqlMagic.displaycon = False;
import duckdb;
import zipfile;
import os;

%load_ext sql
conn = duckdb.connect();
%sql conn --alias duckdb
%sql duckdb:///:memory:
%sql INSTALL zipfs FROM community;
%sql LOAD zipfs;

Note, with the above packages imported, and the correct settings configured now, we can use the Jupyter cell magic %%sql to directly execute SQL code in cells, as opposed to using Python wrappers. Zipfs is community extension provided for DuckDB which allows us to directly load data from zip files behind https links.

In [4]:
%%sql
INSTALL zipfs FROM community;

Empty DataFrame
Columns: [Success]
Index: []

In [5]:
%%sql
LOAD zipfs;

Empty DataFrame
Columns: [Success]
Index: []

In [6]:
%%sql
CREATE TABLE raw_survey AS SELECT * FROM 'C:\Users\ktoto\Desktop\stack-overflow-developer-survey-2025\survey_results_public.csv';

Empty DataFrame
Columns: [Success]
Index: []

## Step 2: Extracting Information
Let us now example the data we have extracted. We'll take a peak at the first ten records to see what's in there.

In [7]:
%%sql
SELECT * FROM raw_survey LIMIT 10;

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NA,NA,NA,ChatGPT,NA,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256,10
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NA,2,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NA,NA,NA,NA,NA,NA,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413,9
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NA,NA,NA,NA,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NA,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061,8
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NA,NA,NA,NA,ChatGPT;Claude Code,NA,When I don’t trust AI’s answers;When I want to...,NA,36197,6
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21,"No, I am not new to coding and did not learn n...",NA,"Yes, I learned how to use AI-enabled tools for...",...,NA,NA,NA,NA,NA,NA,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000,7
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NA,NA,NA,NA,GitHub Copilot,NA,When I have ethical or security concerns about...,designing the architecture in the new domain,120000,7
6,7,I am a developer by profession,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",None of the above,9,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NA,NA,Sentry,NA,ChatGPT;Claude Code;Google Gemini,NA,When I don’t trust AI’s answers;When I need he...,NA,6240,6
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",...,NA,NA,NA,NA,NA,NA,When I want to learn best practices;When I wan...,"Innovation, system design",72000,6
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NA,NA,NA,NA,NA,NA,NA,NA,70000,8
9,10,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NA,NA,NA,NA,NA,NA,When I’m stuck and can’t explain the problem;W...,NA,5400,4

Notice that this information fulfils the definition of data as we discussed in the lessons. Data is a collection of discrete or continues values ultimately, about something we are studying. In reality, collection of data is often influenced by the perspective of those providing or gathering it. In this case, it is influenced by the developers providing answers to the survey system itself. They may answer with biases and with a specific point of view. The survey itself may have designs that orient answers a certain way as well. Data, ultimately comes from the root meaning "as given" - understood to be values about an entity as given (by whatever system or person collected them).

Great - but what descriptive statements can we make about the developer market based on these ten first data records? What is given about the state of software development here? What about if we look at the first thousand records? What about all of the records?

The survey claims to deliver insights and teach us about the state of software development as a practice - and yet, with around ~50,000 responses from ~180 countries on over 300 technologies - isn't it difficult to make descriptive statements about the state of software development?

This is because the data is given about software developers and their practices. Each row represents the response of an individual person. However, to understand the overall software industry, we need to refine this data into knowledge. We need to set a goal to understand the practical difference between raw data, summarized information, and actionable knowledge by transforming the survey results.

Consider the common question: "What is the average salary for developers who know a specific programming language?" By taking the typical steps involved in a common data pipeline (filtering, aggregation, and summarization for example), we can start to see patterns.

In [9]:
%%sql

SELECT
    STRING_SPLIT(LanguageHaveWorkedWith, ';') AS Language,
    MEDIAN(CAST(ConvertedCompYearly AS INT)) AS MedSalary
FROM
    raw_survey
WHERE
    LanguageHaveWorkedWith IS NOT NULL
    AND ConvertedCompYearly IS NOT NULL 
    AND ConvertedCompYearly != 'NA'
GROUP BY --__________  --Language is the solution
LIMIT 20;

                                             Language  MedSalary
0                                                [C#]    70650.5
1   [C#, C++, JavaScript, Python, Visual Basic (.N...    87500.0
2            [C#, JavaScript, PowerShell, TypeScript]   111500.0
3                             [C#, Java, Python, SQL]   145009.0
4          [HTML/CSS, JavaScript, Python, TypeScript]    69609.0
5   [Bash/Shell (all shells), Dart, HTML/CSS, Java...    75410.0
6   [Dart, HTML/CSS, Java, JavaScript, Python, SQL...    24029.0
7   [Bash/Shell (all shells), HTML/CSS, Java, Java...    55687.0
8   [HTML/CSS, Java, JavaScript, PHP, SQL, TypeScr...   116015.0
9                       [C, COBOL, Java, Python, SQL]    63808.0
10  [GDScript, HTML/CSS, Java, JavaScript, Python,...    23616.5
11  [Bash/Shell (all shells), C#, HTML/CSS, Java, ...    81685.0
12  [Bash/Shell (all shells), JavaScript, Python, ...   109054.0
13  [C++, Dart, Groovy, HTML/CSS, Java, JavaScript...    72155.0
14                             [HTML/CSS, JavaScript]    57179.0
15                     [HTML/CSS, JavaScript, Python]    44724.5
16  [Assembly, Bash/Shell (all shells), C, C++, HT...    66000.0
17  [Bash/Shell (all shells), HTML/CSS, JavaScript...   159673.0
18  [Bash/Shell (all shells), C++, HTML/CSS, JavaS...    53710.5
19  [Bash/Shell (all shells), Go, HTML/CSS, JavaSc...    84445.0

Recall that information is fundamentally that which allows us to interpret and understand a studied entity or its abstraction. Note that information sent is not always necessarily the same as information received - and that the information we derive can be different based on who or what is viewing it. For example, you may be surprised to learn about the average salaries above, or you may not - depending on your experience and existing knowledge of the technology sector. 

Despite the cleaner infromation above (i.e. data grouped into categories), we still don't know a lot about software engineering as a practice. Ask yourself for instance, if just by looking at this chart, you could offer guidance to a junior student of software engineering - is that something you would be comfortable doing? I don't think so. Clearly, we need to refine the information further.

## Step 3: Extracting knowledge
Knowledge is a form of awareness, an epistemic truth about the reality which we are concerned with in a given context. Information becomes knowledge when we apply it to build an understanding, and use it to answer a high-value question or to describe an entity in a context. Often, the most justified knowledge is derived through experiments and scientific method - but we just have the data at hand to look at. For the time being, let's narrow our focus to digging through our dataset, so that we can find the highest-paying languages for experienced developers in the three countries with the most responses. This provides actionable insight for a specific type of job, and we will obtain knowledge about software development career opportunities as well as the market for such skilled work.

Task: Modify the query from Part B to filter for results where Country is 'United States of America' and YearsCodePro is between 5 and 10 years.

In [15]:
%%sql
SELECT
    STRING_SPLIT(LanguageHaveWorkedWith, ';') AS Language,
    MEDIAN(CAST(ConvertedCompYearly AS INT)) AS MedSalary,
    CAST(YearsCode AS INT) AS YearsCodingExp
FROM
    raw_survey
WHERE
    LanguageHaveWorkedWith IS NOT NULL
    AND ConvertedCompYearly IS NOT NULL
    AND ConvertedCompYearly != 'NA'
    AND YearsCodingExp BETWEEN 5 AND 10
    AND YearsCode != 'NA'
    AND Country = 'United States of America'
GROUP BY
    Language,
    YearsCodingExp
ORDER BY
    YearsCodingExp DESC
LIMIT 100;

,Language,MedSalary,YearsCodingExp
0,"[Bash/Shell (all shells), C#, PowerShell, Pyth...",70000.0,10
1,"[Bash/Shell (all shells), HTML/CSS, JavaScript...",40000.0,10
2,[Java],187000.0,10
3,"[Bash/Shell (all shells), C#, PHP, PowerShell,...",103000.0,10
4,"[C#, HTML/CSS, JavaScript, PowerShell, Python,...",125000.0,10
...,...,...,...
95,"[Bash/Shell (all shells), Python, SQL]",152500.0,10
96,"[C#, HTML/CSS, JavaScript, PowerShell, SQL, Vi...",66500.0,10
97,"[JavaScript, Python, SQL, TypeScript]",195000.0,10
98,"[Go, HTML/CSS, Java, PowerShell, Python, SQL]",170000.0,10
99,"[Bash/Shell (all shells), Lua, PowerShell, Pyt...",40000.0,10

In [ ]:
%%sql
/* ... SQL query ...
WHERE
    LanguageHaveWorkedWith IS NOT NULL
    AND ConvertedCompYearly IS NOT NULL
    AND ConvertedCompYearly != 'NA'
    AND CAST(YearsCode AS INT) BETWEEN 5 AND 10
    AND YearsCode != 'NA'
    AND Country = 'United States of America'
... */

Now we see more information about the individuals who replied to the survey from the United States, and who have a specific number of years in the field. Next, we'll do the same for people with different years across experience levels, to gain knowledge and understanding about the software engineering career ladder.

In [14]:
%%sql
SELECT
    STRING_SPLIT(LanguageHaveWorkedWith, ';') AS Language,
    MEDIAN(CAST(ConvertedCompYearly AS INT)) AS MedSalary,
    CAST(YearsCode AS INT) AS YearsCodingExp,
    CASE WHEN YearsCodingExp >= 0 AND YearsCodingExp <= 10 THEN ' 0 - 10'
        WHEN YearsCodingExp > 10 AND YearsCodingExp <= 25 THEN '10+ - 25'
        WHEN YearsCodingExp > 25 AND YearsCodingExp <= 50 THEN '50+ - 100'
    END AS YearsCodingExpBucket
FROM
    raw_survey
WHERE
    LanguageHaveWorkedWith IS NOT NULL
    AND ConvertedCompYearly IS NOT NULL
    AND ConvertedCompYearly != 'NA'
    AND YearsCodingExp BETWEEN 5 AND 10
    AND YearsCode != 'NA'
    AND Country = 'United States of America'
GROUP BY
    Language,
    YearsCodingExp
ORDER BY
    YearsCodingExp DESC
LIMIT 100;

,Language,MedSalary,YearsCodingExp,YearsCodingExpBucket
0,"[Assembly, Bash/Shell (all shells), C++, Java,...",95000.0,10,0 - 10
1,"[Bash/Shell (all shells), C, Go, HTML/CSS, Jav...",165000.0,10,0 - 10
2,"[Bash/Shell (all shells), C++, HTML/CSS, Java,...",135000.0,10,0 - 10
3,"[Assembly, Bash/Shell (all shells), C, C++, Go...",150000.0,10,0 - 10
4,"[C, C++, HTML/CSS, Python, Rust]",40000.0,10,0 - 10
...,...,...,...,...
95,"[C#, HTML/CSS, JavaScript, PHP, SQL, Visual Ba...",94000.0,10,0 - 10
96,"[HTML/CSS, Java, JavaScript, TypeScript]",115000.0,10,0 - 10
97,"[HTML/CSS, JavaScript, Ruby, SQL]",131000.0,10,0 - 10
98,"[Bash/Shell (all shells), C++, Python]",160000.0,10,0 - 10
99,"[Bash/Shell (all shells), C#, PHP, PowerShell,...",103000.0,10,0 - 10

Note this still doesn't help us much. Many of the developers use multiple languages, and there are so many combinations of languages one could use, it becomes confusing for us to understand how pay is impacted by years of experience. Let's focus in on one set of commonly used languages.

In [44]:
%%sql
SELECT
    'Rust' AS Language,
    MEDIAN(CAST(ConvertedCompYearly AS INT)) AS MedSalary,
    CASE WHEN CAST(YearsCode AS INT)  >= 0 AND CAST(YearsCode AS INT)  <= 10 THEN ' 0 - 10'
        WHEN CAST(YearsCode AS INT)  > 10 AND CAST(YearsCode AS INT)  <= 25 THEN '10+ - 25'
        WHEN CAST(YearsCode AS INT)  > 25 AND CAST(YearsCode AS INT)  <= 50 THEN '50+ - 100'
    END AS YearsCodingExpBucket
FROM
    raw_survey
WHERE
    LanguageHaveWorkedWith IS NOT NULL
    AND ConvertedCompYearly IS NOT NULL
    AND ConvertedCompYearly != 'NA'
    AND YearsCode != 'NA'
    AND YearsCodingExpBucket != 'None'
    AND Country = 'United States of America'
    AND 'Rust' IN STRING_SPLIT(LanguageHaveWorkedWith, ';') 
GROUP BY
    Language,
    YearsCodingExpBucket
ORDER BY
    YearsCodingExpBucket DESC
LIMIT 100;

  Language  MedSalary YearsCodingExpBucket
0     Rust   200000.0            50+ - 100
1     Rust   170000.0             10+ - 25
2     Rust    91000.0               0 - 10

In [45]:
%%sql
SELECT
    'C++' AS Language,
    MEDIAN(CAST(ConvertedCompYearly AS INT)) AS MedSalary,
    CASE WHEN CAST(YearsCode AS INT)  >= 0 AND CAST(YearsCode AS INT)  <= 10 THEN ' 0 - 10'
        WHEN CAST(YearsCode AS INT)  > 10 AND CAST(YearsCode AS INT)  <= 25 THEN '10+ - 25'
        WHEN CAST(YearsCode AS INT)  > 25 AND CAST(YearsCode AS INT)  <= 50 THEN '50+ - 100'
    END AS YearsCodingExpBucket
FROM
    raw_survey
WHERE
    LanguageHaveWorkedWith IS NOT NULL
    AND ConvertedCompYearly IS NOT NULL
    AND ConvertedCompYearly != 'NA'
    AND YearsCode != 'NA'
    AND YearsCodingExpBucket != 'None'
    AND Country = 'United States of America'
    AND 'C++' IN STRING_SPLIT(LanguageHaveWorkedWith, ';') 
GROUP BY
    Language,
    YearsCodingExpBucket
ORDER BY
    YearsCodingExpBucket DESC
LIMIT 100;

  Language  MedSalary YearsCodingExpBucket
0      C++   175000.0            50+ - 100
1      C++   145000.0             10+ - 25
2      C++    90000.0               0 - 10

Comparing the newer language, we see that those learning Rust through their careers experience significant salary increases as their career continues. What happens if we combine those who know both C++ and Rust?

In [47]:
%%sql
SELECT
    'C++ and Rust' AS Language,
    MEDIAN(CAST(ConvertedCompYearly AS INT)) AS MedSalary,
    CASE WHEN CAST(YearsCode AS INT)  >= 0 AND CAST(YearsCode AS INT)  <= 10 THEN ' 0 - 10'
        WHEN CAST(YearsCode AS INT)  > 10 AND CAST(YearsCode AS INT)  <= 25 THEN '10+ - 25'
        WHEN CAST(YearsCode AS INT)  > 25 AND CAST(YearsCode AS INT)  <= 50 THEN '50+ - 100'
    END AS YearsCodingExpBucket
FROM
    raw_survey
WHERE
    LanguageHaveWorkedWith IS NOT NULL
    AND ConvertedCompYearly IS NOT NULL
    AND ConvertedCompYearly != 'NA'
    AND YearsCode != 'NA'
    AND YearsCodingExpBucket != 'None'
    AND Country = 'United States of America'
    AND 'C++' IN STRING_SPLIT(LanguageHaveWorkedWith, ';') 
    AND 'Rust' IN STRING_SPLIT(LanguageHaveWorkedWith, ';') 
GROUP BY
    Language,
    YearsCodingExpBucket
ORDER BY
    YearsCodingExpBucket DESC
LIMIT 100;

       Language  MedSalary YearsCodingExpBucket
0  C++ and Rust   206000.0            50+ - 100
1  C++ and Rust   150000.0             10+ - 25
2  C++ and Rust    80000.0               0 - 10

We now see and understand more of the career ladder. Rust is growing language and it appears there is considerable demand for it.

How does this compare with those who work with databases?!

In [54]:
%%sql
SELECT
    CASE WHEN 'MongoDB' IN STRING_SPLIT(DatabaseHaveWorkedWith, ';') AND 'PostgreSQL' IN STRING_SPLIT(DatabaseHaveWorkedWith, ';') THEN 'MongoDB & PostgreSQL'
         WHEN 'MongoDB' IN STRING_SPLIT(DatabaseHaveWorkedWith, ';') THEN 'MongoDB'
         WHEN 'PostgreSQL' IN STRING_SPLIT(DatabaseHaveWorkedWith, ';') THEN 'PostgreSQL' END AS DatabaseExp,
    MEDIAN(CAST(ConvertedCompYearly AS INT)) AS MedSalary,
    CASE WHEN CAST(YearsCode AS INT)  >= 0 AND CAST(YearsCode AS INT)  <= 10 THEN ' 0 - 10'
        WHEN CAST(YearsCode AS INT)  > 10 AND CAST(YearsCode AS INT)  <= 25 THEN '10+ - 25'
        WHEN CAST(YearsCode AS INT)  > 25 AND CAST(YearsCode AS INT)  <= 50 THEN '50+ - 100'
    END AS YearsCodingExpBucket
FROM
    raw_survey
WHERE
    DatabaseExp IS NOT NULL
    AND ConvertedCompYearly IS NOT NULL
    AND ConvertedCompYearly != 'NA'
    AND YearsCode != 'NA'
    AND YearsCodingExpBucket != 'None'
    AND Country = 'United States of America'
    AND ('MongoDB' IN DatabaseExp OR 'PostgreSQL' IN DatabaseExp)
GROUP BY
    DatabaseExp,
    YearsCodingExpBucket
ORDER BY
    DatabaseExp, YearsCodingExpBucket DESC
LIMIT 100;

            DatabaseExp  MedSalary YearsCodingExpBucket
0               MongoDB   165000.0            50+ - 100
1               MongoDB   150000.0             10+ - 25
2               MongoDB    95750.0               0 - 10
3  MongoDB & PostgreSQL   185000.0            50+ - 100
4  MongoDB & PostgreSQL   170000.0             10+ - 25
5  MongoDB & PostgreSQL   122000.0               0 - 10
6            PostgreSQL   184500.0            50+ - 100
7            PostgreSQL   168000.0             10+ - 25
8            PostgreSQL   112000.0               0 - 10

## Standout: 
What are some potential pitfalls of this type of analysis? We believe we have found some patterns we know to be true, but how could we have erred in coming to these conclusions?