# Exercise 2: Creating Anomalies

In [1]:
%%capture
%config SqlMagic.autopandas = True;
%config SqlMagic.feedback = False;
%config SqlMagic.displaycon = False;
import duckdb;
import pandas as pd
import zipfile;
import os;
from io import StringIO
import psycopg2
from psycopg2 import Error
%load_ext sql
%sql postgresql://postgres:postgres@127.0.0.1:5432/postgres

In [2]:
%%sql
-- Drop all tables if they exist (to start fresh)
DROP TABLE IF EXISTS CustomerAccounts;
DROP TABLE IF EXISTS Customers CASCADE;
DROP TABLE IF EXISTS Accounts;

Empty DataFrame
Columns: []
Index: []

In [3]:
%%sql
BEGIN;
/*
 * This is a "denormalized" table. We've combined customer and
 * account information into a single row.
 * Notice the REDUNDANT data: 'Alice Smith' and her email
 * are repeated for every account she owns.
 */
 
DROP TABLE IF EXISTS CustomerAccounts;
CREATE TABLE CustomerAccounts (
    account_id  INT PRIMARY KEY, -- We'll use this as the primary key
    customer_id INT NOT NULL,
    full_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(100),
    balance     DECIMAL(10, 2) NOT NULL
);

-- Load the data
INSERT INTO CustomerAccounts (account_id, customer_id, full_name, email, balance) VALUES
(101, 1, 'Alice Smith', 'alice@example.com', 1000.00),
(102, 2, 'Bob Johnson', 'bob@example.com', 250.00),
(103, 1, 'Alice Smith', 'alice@example.com', 750.00); -- Alice's second account
COMMIT;

Empty DataFrame
Columns: []
Index: []

### 1. The UPDATE Anomaly (Inconsistent Data)

### Task 1 - Goal: Alice has a new email address, 'alice.new@example.com'. We need to update her customer record. Use 'SET email = alice.new@example.com' to do so.

In [4]:
%%sql
BEGIN;
UPDATE CustomerAccounts
SET email = 'alice.new@example.com'
WHERE account_id = 101;
COMMIT;

Empty DataFrame
Columns: []
Index: []

In [5]:
%%sql
SELECT * FROM CustomerAccounts WHERE customer_id = 1;

   account_id  customer_id    full_name                  email  balance
0         103            1  Alice Smith      alice@example.com   750.00
1         101            1  Alice Smith  alice.new@example.com  1000.00

### Task 2: Fill in the Delete statement where clause for Bob's account

In [6]:
%%sql
BEGIN;
DELETE FROM CustomerAccounts
WHERE account_id = 102;
COMMIT;

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql
SELECT * FROM CustomerAccounts WHERE customer_id = 2;

Empty DataFrame
Columns: [account_id, customer_id, full_name, email, balance]
Index: []

In [8]:
%%sql
BEGIN;
INSERT INTO CustomerAccounts (customer_id, full_name, email)
VALUES (3, 'Charlie Day', 'charlie@example.com');
COMMIT;

RuntimeError: (psycopg2.errors.NotNullViolation) null value in column "account_id" of relation "customeraccounts" violates not-null constraint
DETAIL:  Failing row contains (null, 3, Charlie Day, charlie@example.com, null).

[SQL: INSERT INTO CustomerAccounts (customer_id, full_name, email)
VALUES (3, 'Charlie Day', 'charlie@example.com');]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [9]:
%%sql
ROLLBACK;

Empty DataFrame
Columns: []
Index: []

### Task 3: Normalize the schema below. Fill in the query with customer_id and full_name

In [10]:
%%sql
BEGIN;
DROP TABLE IF EXISTS CustomerAccounts;
DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS Customers;
CREATE TABLE Customers (
    customer_id INT PRIMARY KEY, 
    full_name VARCHAR(100) NOT NULL, 
    email VARCHAR(100) NOT NULL UNIQUE ); 

CREATE TABLE Accounts (
    account_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    balance DECIMAL(10, 2) NOT NULL CHECK (balance >= 0),
    CONSTRAINT fk_customer FOREIGN KEY(customer_id) REFERENCES Customers(customer_id) ); 

INSERT INTO Customers (customer_id, full_name, email) VALUES (1, 'Alice Smith', 'alice@example.com'), (2, 'Bob Johnson', 'bob@example.com'); 
INSERT INTO Accounts (account_id, customer_id, balance) VALUES (101, 1, 1000.00), (102, 2, 250.00), (103, 1, 750.00); -- Alice's second account
COMMIT;

Empty DataFrame
Columns: []
Index: []

In [11]:
%%sql
BEGIN;
UPDATE Customers
SET email = 'alice.new@example.com'
WHERE customer_id = 1;
COMMIT;

Empty DataFrame
Columns: []
Index: []

In [12]:
%%sql
SELECT * FROM Customers WHERE customer_id = 1;

   customer_id    full_name                  email
0            1  Alice Smith  alice.new@example.com

In [13]:
%%sql
SELECT * FROM Accounts WHERE customer_id = 1;

   account_id  customer_id  balance
0         101            1  1000.00
1         103            1   750.00

In [14]:
%%sql
BEGIN;
DELETE FROM Accounts
WHERE account_id = 102;
COMMIT;

Empty DataFrame
Columns: []
Index: []

In [15]:
%%sql
SELECT * FROM Accounts WHERE customer_id = 2; -- (Returns 0 rows)

Empty DataFrame
Columns: [account_id, customer_id, balance]
Index: []

In [16]:
%%sql
SELECT * FROM Customers WHERE customer_id = 2; -- (Returns 1 row)

   customer_id    full_name            email
0            2  Bob Johnson  bob@example.com

In [17]:
%%sql
BEGIN;
INSERT INTO Customers (customer_id, full_name, email)
VALUES (3, 'Charlie Day', 'charlie@example.com');
COMMIT;

Empty DataFrame
Columns: []
Index: []

In [18]:
%%sql
SELECT * FROM Customers WHERE customer_id = 3;

   customer_id    full_name                email
0            3  Charlie Day  charlie@example.com

In [19]:
%%sql
SELECT * FROM Accounts WHERE customer_id = 3;

Empty DataFrame
Columns: [account_id, customer_id, balance]
Index: []